sudo: required
services:
  - docker

before_install:
  - docker build -t csilva/linkyoh-app .
  - docker build -t devstbz/linkyoh-nginx-app ./nginx

script:
  - docker images


after_success:
  - docker build -t devstbz/linkyoh-app .
  - docker build -t devstbz/linkyoh-nginx-app ./nginx

  # Log into the docker cli

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push devstbz/linkyoh-app
  - docker push devstbz/linkyoh-nginx-app


deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "linkyoh"
  env: "Linkyoh-env"
  bucket_name: "elasticbeanstalk-us-west-2-323216669271"
  bucket_path: "linkyoh"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
