dbuser = ['ADD VALUE HERE']
dbpassword = ['ADD VALUE HERE']
dbname = ['ADD VALUE HERE']
dbhome = ['ADD VALUE HERE']
dbport = ['ADD VALUE HERE']

EMAIL_BACKEND = ['ADD VALUE HERE']
EMAIL_HOST = ['ADD VALUE HERE']
EMAIL_HOST_USER = ['ADD VALUE HERE']
EMAIL_HOST_PASSWORD = ['ADD VALUE HERE']
EMAIL_PORT = [ADD VALUE HERE]
EMAIL_USE_TLS = [ADD VALUE HERE]
EMAIL_USE_SSL = [ADD VALUE HERE]
DEFAULT_FROM_EMAIL = ['ADD VALUE HERE']
SEND_TO_EMAIL = ['ADD VALUE HERE']

SOCIAL_AUTH_FACEBOOK_KEY = ['ADD VALUE HERE']
SOCIAL_AUTH_FACEBOOK_SECRET = ['ADD VALUE HERE']

SECRET_KEY = ['ADD VALUE HERE']

ALLOWED_HOST = ['ADD VALUE HERE']
ALLOWED_HOST1 = ['ADD VALUE HERE']
ALLOWED_HOST2 = ['ADD VALUE HERE']
ALLOWED_HOST3 = ['ADD VALUE HERE']

merchant_id = ["ADD VALUE HERE"]
public_key = ["ADD VALUE HERE"]
private_key = ["ADD VALUE HERE"]