version: "3"

services:
  web:
    restart: always
    build:
      context: .
    volumes:
      - .:/linkyoh
      - static_volume:/linkyoh/static
      - media_volume:/linkyoh/media
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate && exec gunicorn linkyoh.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    environment:
      - LYDEPLOYMENT_MODE=standalone
      - LYDEBUG=${LYDEBUG}
      - LYDBUSER=${LYDBUSER}
      - LYDB_PASSWORD=${LYDB_PASSWORD}
      - LYDB_NAME=${LYDB_NAME}
      - LYDB_HOST=${LYDB_HOST}
      - LYDB_PORT=${LYDB_PORT}
      - LYEMAIL_BACKEND=${LYEMAIL_BACKEND}
      - LYEMAIL_HOST=${LYEMAIL_HOST}
      - LYEMAIL_HOST_USER=${LYEMAIL_HOST_USER}
      - LYEMAIL_HOST_PASSWORD=${LYEMAIL_HOST_PASSWORD}
      - LYEMAIL_PORT=${LYEMAIL_PORT}
      - LYEMAIL_TLS=${LYEMAIL_TLS}
      - LYEMAIL_SSL=${LYEMAIL_SSL}
      - LYDEFAULT_EMAIL=${LYDEFAULT_EMAIL}
      - LYSEND_TO_EMAIL=${LYSEND_TO_EMAIL}
      - LYFB_KEY=${LYFB_KEY}
      - LYFB_SECRET=${LYFB_SECRET}
      - LYAPP_SECRET=${LYAPP_SECRET}
      - LYAH0=${LYAH0}
      - LYAH1=${LYAH1}
      - LYAH2=${LYAH2}
      - LYAH3=${LYAH3}
      - LYMERCHANT_ID=${LYMERCHANT_ID}
      - LYMERCHANT_PUBLIC=${LYMERCHANT_PUBLIC}
      - LYMERCHANT_PRIVATE=${LYMERCHANT_PRIVATE}
    env_file:
      - .env

  nginx:
    restart: always
    build:
      context: ./nginx
    image: nginx:1.15-alpine
    volumes:
      - ./nginx/nginx:/etc/nginx/conf.d
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
      - static_volume:/linkyoh/static
      - media_volume:/linkyoh/media
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'envsubst \"\\$${DOMAIN_NAME}\" < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME:-linkyoh.com}

  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME:-linkyoh.com}

volumes:
  static_volume:
  media_volume:
