version: "3"

services:
  web:
    build:
      context: .
    volumes:
      - .:/linkyoh
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate && exec gunicorn linkyoh.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    environment:
      - LYDBUSER
      - LYDB_PASSWORD
      - LYDB_NAME
      - LYDB_HOST
      - LYDB_PORT
      - LYEMAIL_BACKEND
      - LYEMAIL_HOST
      - LYEMAIL_HOST_USER
      - LYEMAIL_HOST_PASSWORD
      - LYEMAIL_PORT
      - LYEMAIL_TLS
      - LYEMAIL_SSL
      - LYDEFAULT_EMAIL
      - LYSEND_TO_EMAIL
      - LYFB_KEY
      - LYFB_SECRET
      - LYAPP_SECRET
      - LYAH0
      - LYAH1
      - LYAH2
      - LYAH3
      - LYLYMERCHANT_ID
      - LYMERCHANT_PUBLIC
      - LYMERCHANT_PRIVATE
    env_file:
      - .env

  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"