version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: linkyoh_rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ main port
      - "15672:15672" # RabbitMQ management UI
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped
    networks:
      - linkyoh_network

  celery_worker:
    build: .
    container_name: linkyoh_celery_worker
    command: celery -A linkyoh worker -l info
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
      - web
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    restart: unless-stopped
    networks:
      - linkyoh_network

  celery_beat:
    build: .
    container_name: linkyoh_celery_beat
    command: celery -A linkyoh beat -l info
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
      - web
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    restart: unless-stopped
    networks:
      - linkyoh_network

  # Include the web service from the main docker-compose.yml
  web:
    extends:
      file: docker-compose.yml
      service: web
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    depends_on:
      - rabbitmq
    networks:
      - linkyoh_network

volumes:
  rabbitmq_data:

networks:
  linkyoh_network:
    driver: bridge