version: "3.3"
services:
  web:
    build:
      context: .
    container_name: linkyoh_web
    restart: always
    volumes:
      - .:/linkyoh
      - static_volume:/linkyoh/static
      - media_volume:/linkyoh/media
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             gunicorn linkyoh.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    environment:
      - LYDEBUG=${LYDEBUG}
      - LYDBUSER=${LYDBUSER}
      - LYDB_PASSWORD=${LYDB_PASSWORD}
      - LYDB_NAME=${LYDB_NAME}
      - LYDB_HOST=${LYDB_HOST}
      - LYDB_PORT=${LYDB_PORT}
      - LYEMAIL_BACKEND=${LYEMAIL_BACKEND}
      - LYEMAIL_HOST=${LYEMAIL_HOST}
      - LYEMAIL_HOST_USER=${LYEMAIL_HOST_USER}
      - LYEMAIL_HOST_PASSWORD=${LYEMAIL_HOST_PASSWORD}
      - LYEMAIL_PORT=${LYEMAIL_PORT}
      - LYEMAIL_TLS=${LYEMAIL_TLS}
      - LYEMAIL_SSL=${LYEMAIL_SSL}
      - LYDEFAULT_EMAIL=${LYDEFAULT_EMAIL}
      - LYSEND_TO_EMAIL=${LYSEND_TO_EMAIL}
      - LYFB_KEY=${LYFB_KEY}
      - LYFB_SECRET=${LYFB_SECRET}
      - LYAPP_SECRET=${LYAPP_SECRET}
      - LYAH0=${LYAH0}
      - LYAH1=${LYAH1}
      - LYAH2=${LYAH2}
      - LYAH3=${LYAH3}
      - LYLYMERCHANT_ID=${LYLYMERCHANT_ID}
      - LYMERCHANT_PUBLIC=${LYMERCHANT_PUBLIC}
      - LYMERCHANT_PRIVATE=${LYMERCHANT_PRIVATE}
    env_file:
      - .env

  nginx:
    build: 
      context: ./nginx
    container_name: linkyoh_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx:/etc/nginx/conf.d
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
      - static_volume:/linkyoh/static
      - media_volume:/linkyoh/media
    # The following command: reloads Nginx every 6 hours in background, 
    # then runs nginx in the foreground:
    command: >
      sh -c "while :; do
               sleep 6h && nginx -s reload;
             done & 
             nginx -g 'daemon off;'"

  certbot:
    image: certbot/certbot:latest
    container_name: linkyoh_certbot
    restart: always
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    # Renew every 12 hours; reload Nginx if a cert is actually renewed
    entrypoint: >
      sh -c "trap exit TERM;
             while :; do
               certbot renew --webroot -w /var/www/certbot --quiet --agree-tos && 
               echo 'Reloading nginx...' &&
               nginx -s reload 2>/dev/null || true;
               sleep 12h;
             done;"

volumes:
  static_volume:
  media_volume:
