version: '3.7'

services:
  web:
    build: .
    command: python /linkyoh/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/linkyoh
#    ports:
#      - 8000:8000

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
