# Generated by Django 2.0.7 on 2018-07-29 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkyohapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slogan',
            field=models.CharField(default='My Slogan', max_length=500),
            preserve_default=False,
        ),
    ]
