# Generated by Django 2.0.7 on 2018-07-30 20:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('linkyohapp', '0008_gig_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=128)),
                ('short_category', models.CharField(max_length=8)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.CharField(max_length=128)),
                ('sub_short_category', models.CharField(max_length=8)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linkyohapp.Category')),
            ],
        ),
        migrations.AlterField(
            model_name='gig',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
