# Generated by Django 2.0.7 on 2018-08-26 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linkyohapp', '0017_rating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='linkyohapp.Rating'),
            preserve_default=False,
        ),
    ]
