# Generated by Django 2.1.7 on 2019-03-04 20:49

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('linkyohapp', '0021_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, unique=True)),
                ('category', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=32)),
                ('body', models.TextField()),
            ],
        ),
    ]
