# Generated by Django 2.2.3 on 2022-02-28 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkyohapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_phone_number',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='link',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='locale',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='timezone',
        ),
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
