# Generated by Django 2.2.3 on 2025-06-21 12:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import linkyohapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('linkyohapp', '0002_auto_20220227_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='GigServiceArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linkyohapp.District')),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_areas', to='linkyohapp.Gig')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linkyohapp.Location')),
            ],
            options={
                'verbose_name': 'Service Area',
                'verbose_name_plural': 'Service Areas',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GigImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=linkyohapp.models.gig_image_upload_path)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='linkyohapp.Gig')),
            ],
            options={
                'ordering': ['order', 'created'],
            },
        ),
        migrations.CreateModel(
            name='GigContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{7,15}$')])),
                ('description', models.CharField(blank=True, max_length=100)),
                ('is_whatsapp', models.BooleanField(default=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='linkyohapp.Gig')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
