# Generated by Django 2.0.7 on 2018-07-30 02:30

from django.db import migrations, models
import linkyohapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('linkyohapp', '0002_profile_slogan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='photo',
            field=models.FileField(default='gigs_img/empty_cover.jpg', upload_to=linkyohapp.models.cover_upload_path),
        ),
    ]
