# Generated by Django 2.2.3 on 2025-06-22 15:23

from django.db import migrations, models
import linkyohapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('linkyohapp', '0004_auto_20250621_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to=linkyohapp.models.profile_cover_upload_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='profile_avatars/'),
        ),
    ]
