# Generated by Django 2.0.7 on 2018-07-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkyohapp', '0004_auto_20180730_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='address_1',
            field=models.CharField(default='test address', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gig',
            name='address_2',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
