# Generated by Django 2.2.3 on 2025-06-22 22:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import linkyohapp.models_ad


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('linkyohapp', '0006_profile_show_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdPlacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('home_hero', 'Home Page - Hero Banner'), ('home_featured', 'Home Page - Featured Section'), ('home_categories', 'Home Page - Between Categories'), ('home_how_it_works', 'Home Page - After How It Works'), ('home_reviews', 'Home Page - After Reviews'), ('home_latest', 'Home Page - Within Latest Services'), ('home_footer', 'Home Page - Before Footer'), ('category_top', 'Category Page - Top'), ('category_bottom', 'Category Page - Bottom'), ('category_inline', 'Category Page - Inline with Results'), ('gig_detail_top', 'Gig Detail Page - Top'), ('gig_detail_bottom', 'Gig Detail Page - Bottom'), ('gig_detail_sidebar', 'Gig Detail Page - Sidebar'), ('profile_top', 'Profile Page - Top'), ('profile_bottom', 'Profile Page - Bottom'), ('search_top', 'Search Results - Top'), ('search_inline', 'Search Results - Inline with Results'), ('search_bottom', 'Search Results - Bottom'), ('global_header', 'Global - Below Header'), ('global_footer', 'Global - Above Footer')], max_length=50, unique=True)),
                ('description', models.TextField(help_text='Description of where this ad placement appears')),
                ('is_active', models.BooleanField(default=True)),
                ('max_ads', models.PositiveIntegerField(default=1, help_text='Maximum number of ads to show in this placement')),
                ('recommended_width', models.PositiveIntegerField(blank=True, help_text='Recommended width in pixels', null=True)),
                ('recommended_height', models.PositiveIntegerField(blank=True, help_text='Recommended height in pixels', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ad Placement',
                'verbose_name_plural': 'Ad Placements',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AdPlacementAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ad Placement Assignment',
                'verbose_name_plural': 'Ad Placement Assignments',
                'ordering': ['-priority', 'ad__title'],
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=linkyohapp.models_ad.ad_image_upload_path)),
                ('html_content', models.TextField(blank=True, help_text='HTML content for the ad (if not using an image)')),
                ('destination_url', models.URLField(help_text='URL where users will be directed when clicking the ad')),
                ('ad_type', models.CharField(choices=[('banner', 'Banner Ad'), ('card', 'Card Ad'), ('text', 'Text Ad'), ('sponsored', 'Sponsored Listing')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('max_impressions', models.PositiveIntegerField(blank=True, help_text='Maximum number of impressions for this ad', null=True)),
                ('total_impressions', models.PositiveIntegerField(default=0)),
                ('total_clicks', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to=settings.AUTH_USER_MODEL)),
                ('placements', models.ManyToManyField(through='linkyohapp.AdPlacementAssignment', to='linkyohapp.AdPlacement')),
                ('target_categories', models.ManyToManyField(blank=True, related_name='targeted_ads', to='linkyohapp.Category')),
                ('target_districts', models.ManyToManyField(blank=True, related_name='targeted_ads', to='linkyohapp.District')),
            ],
            options={
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='adplacementassignment',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linkyohapp.Advertisement'),
        ),
        migrations.AddField(
            model_name='adplacementassignment',
            name='placement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linkyohapp.AdPlacement'),
        ),
        migrations.CreateModel(
            name='AdImpression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='linkyohapp.Advertisement')),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linkyohapp.AdPlacement')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ad Impression',
                'verbose_name_plural': 'Ad Impressions',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AdClick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='linkyohapp.Advertisement')),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linkyohapp.AdPlacement')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ad Click',
                'verbose_name_plural': 'Ad Clicks',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='adplacementassignment',
            unique_together={('ad', 'placement')},
        ),
    ]
