# Generated by Django 2.0.7 on 2018-07-30 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linkyohapp', '0006_auto_20180730_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='location',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='linkyohapp.Location'),
            preserve_default=False,
        ),
    ]
