# Generated by Django 2.0.7 on 2018-07-30 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linkyohapp', '0007_gig_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='state',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='linkyohapp.State'),
            preserve_default=False,
        ),
    ]
