# Generated by Django 2.2.3 on 2025-06-30 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkyohapp', '0008_phoneverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='call_for_pricing',
            field=models.BooleanField(default=False, help_text="Hide price and show 'Call for pricing details' instead"),
        ),
        migrations.AlterField(
            model_name='gig',
            name='price',
            field=models.IntegerField(default=0, help_text="Use -1 for 'Call for pricing'"),
        ),
    ]
