# Generated by Django 2.0.7 on 2018-07-30 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linkyohapp', '0009_auto_20180730_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='sub_category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='linkyohapp.SubCategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gig',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linkyohapp.Category'),
        ),
    ]
