# Generated by Django 2.2.3 on 2025-07-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkyohapp', '0009_auto_20250630_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='featured',
            field=models.BooleanField(default=False, help_text='Featured across the entire site'),
        ),
        migrations.AddField(
            model_name='gig',
            name='featured_in_category',
            field=models.BooleanField(default=False, help_text='Featured within its category'),
        ),
        migrations.AddField(
            model_name='gig',
            name='featured_in_district',
            field=models.BooleanField(default=False, help_text='Featured within its district'),
        ),
        migrations.AddField(
            model_name='gig',
            name='featured_in_location',
            field=models.BooleanField(default=False, help_text='Featured within its location'),
        ),
        migrations.AddField(
            model_name='gig',
            name='featured_in_subcategory',
            field=models.BooleanField(default=False, help_text='Featured within its subcategory'),
        ),
    ]
