# Generated by Django 3.2.20 on 2025-07-25 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('linkyohapp', '0010_auto_20250724_1323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalcountry',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical country', 'verbose_name_plural': 'historical countrys'},
        ),
        migrations.AlterModelOptions(
            name='historicaldistrict',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical district', 'verbose_name_plural': 'historical districts'},
        ),
        migrations.AlterModelOptions(
            name='historicallocal',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical local', 'verbose_name_plural': 'historical locals'},
        ),
        migrations.AlterModelOptions(
            name='historicallocaltype',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical local type', 'verbose_name_plural': 'historical local types'},
        ),
        migrations.AlterModelOptions(
            name='historicallocation',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical location', 'verbose_name_plural': 'historical locations'},
        ),
        migrations.AlterField(
            model_name='historicalcountry',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaldistrict',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicallocal',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicallocaltype',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicallocation',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('metric_type', models.CharField(choices=[('view', 'View'), ('contact_click', 'Contact Click'), ('share', 'Share'), ('favorite', 'Favorite'), ('category_view', 'Category View'), ('subcategory_view', 'Subcategory View'), ('search', 'Search')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='linkyohapp.category')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('gig', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='linkyohapp.gig')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='linkyohapp.subcategory')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stat',
                'verbose_name_plural': 'Stats',
            },
        ),
        migrations.AddIndex(
            model_name='stats',
            index=models.Index(fields=['created_at'], name='linkyohapp__created_e6cd58_idx'),
        ),
        migrations.AddIndex(
            model_name='stats',
            index=models.Index(fields=['metric_type'], name='linkyohapp__metric__e82fc9_idx'),
        ),
        migrations.AddIndex(
            model_name='stats',
            index=models.Index(fields=['gig'], name='linkyohapp__gig_id_ff8113_idx'),
        ),
        migrations.AddIndex(
            model_name='stats',
            index=models.Index(fields=['category'], name='linkyohapp__categor_f17028_idx'),
        ),
        migrations.AddIndex(
            model_name='stats',
            index=models.Index(fields=['subcategory'], name='linkyohapp__subcate_420457_idx'),
        ),
    ]
