# Generated by Django 3.2.20 on 2025-07-28 00:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('linkyohapp', '0011_auto_20250724_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='GigClaimRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{7,15}$')])),
                ('reason', models.TextField(help_text='Explain why you should be the owner of this gig')),
                ('supporting_document', models.FileField(blank=True, help_text='Upload any supporting documents (business license, ID, etc.)', null=True, upload_to='claim_documents/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes about this claim request')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_requests', to='linkyohapp.gig')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gig_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gig Claim Request',
                'verbose_name_plural': 'Gig Claim Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
