# Generated by Django 2.0.7 on 2018-08-03 22:00

from django.db import migrations, models
import linkyohapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('linkyohapp', '0012_auto_20180731_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.FileField(default='category_img/linkyoh_banner_web.png', upload_to=linkyohapp.models.banner_upload_path),
        ),
    ]
