# Generated by Django 2.0.7 on 2018-08-06 01:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('linkyohapp', '0014_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
