# Generated by Django 3.2.20 on 2026-05-19 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('linkyohapp', '0015_auto_20250801_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedGigSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('source_notes', models.TextField(blank=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_import_sources', to='linkyohapp.gig')),
                ('gig', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='import_source', to='linkyohapp.gig')),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_gig_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Imported Gig Source',
                'verbose_name_plural': 'Imported Gig Sources',
                'ordering': ['-created_at'],
            },
        ),
    ]
