# Generated by Django 2.0.7 on 2018-08-26 23:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('linkyohapp', '0018_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
