# Generated by Django 2.1.4 on 2019-01-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkyohapp', '0019_gig_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('job_title', models.CharField(blank=True, max_length=30)),
                ('bio', models.TextField(blank=True)),
            ],
        ),
    ]
